### ISSUE TITLE
Templating issue in IE11

### ISSUE THREAD

**Issue by maeligg** [LeaVerou/markapp#36]
This is what I see using IE 11.0.9600 on Windows 7 :
![markapp_ie](https://cloud.githubusercontent.com/assets/9273118/18387087/c9b1ce62-769a-11e6-899b-6a06b4d63e45.PNG)

No errors or warnings in the console.

**Comment by LeaVerou** [comment]
Do you actually use IE11 as your main browser?

**Comment by maeligg** [comment]
No, I just happened to open the site while testing something else. I appreciate the issue is unlikely to come up for most devs, though.

**Comment by LeaVerou** [comment]
Yup. A site's browser compat is a function of its users. Developer sites don't need to work in IE11, because there is no developer that uses IE11 as their main browser. :)
